### ISSUE TITLE
Rsi problem 

### ISSUE THREAD

**Issue by COBRA-StakePool** [aqs-base/acuitas-issues#33]
Version 1.2.3
Rsi don't want to enter in live trade. Even when doing manual trade. It's not a problem all the time. I close the trader and restart the computer and entered. 

I got enough funds  to do the trade

Log:
2021-02-04 02:02:17 DEBUG ExchangeOrderLog - exception e: {}
org.knowm.xchange.exceptions.OperationTimeoutException: Timestamp for this request is outside of the recvWindow.
  at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:43) ~[crowtrader-Server-v1.2.3.jar:?]
  at org.knowm.xchange.binance.service.BinanceTradeService.getTradeHistory(BinanceTradeService.java:298) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.acuitas.exchanges.adapters.trading.binance.BinanceTradingExchangeAdapter.syncTradeHistory(BinanceTradingExchangeAdapter.java:299) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.acuitas.exchanges.ExchangeService.syncProcessTradeHistory(ExchangeService.java:306) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.acuitas.system.services.exchange.ExchangeHistoryManager.lambda$start$0(ExchangeHistoryManager.java:73) ~[crowtrader-Server-v1.2.3.jar:?]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.knowm.xchange.binance.dto.BinanceException: Timestamp for this request is outside of the recvWindow.
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:189) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:421) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[crowtrader-Server-v1.2.3.jar:?]
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163) ~[crowtrader-Server-v1.2.3.jar:?]
  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) ~[crowtrader-Server-v1.2.3.jar:?]
at com.sun.proxy.$Proxy40.myTrades(Unknown Source) ~[?:?]
  at org.knowm.xchange.binance.service.BinanceTradeServiceRaw.myTrades(BinanceTradeServiceRaw.java:152) ~[crowtrader-Server-v1.2.3.jar:?]
  at org.knowm.xchange.binance.service.BinanceTradeService.getTradeHistory(BinanceTradeService.java:278) ~[crowtrader-Server-v1.2.3.jar:?]
  ... 10 more
2021-02-04 02:02:17 DEBUG ExchangeOrderLog - exception e: org.knowm.xchange.exceptions.OperationTimeoutException: Timestamp for this request is outside of the recvWindow.
  at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:43)
  at org.knowm.xchange.binance.service.BinanceTradeService.getTradeHistory(BinanceTradeService.java:298)
  at com.acuitas.exchanges.adapters.trading.binance.BinanceTradingExchangeAdapter.syncTradeHistory(BinanceTradingExchangeAdapter.java:299)
  at com.acuitas.exchanges.ExchangeService.syncProcessTradeHistory(ExchangeService.java:306)
  at com.acuitas.system.services.exchange.ExchangeHistoryManager.lambda$start$0(ExchangeHistoryManager.java:73)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: org.knowm.xchange.binance.dto.BinanceException: Timestamp for this request is outside of the recvWindow.
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
  at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
  at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:189)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:421)
  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
  at com.sun.proxy.$Proxy40.myTrades(Unknown Source)
  at org.knowm.xchange.binance.service.BinanceTradeServiceRaw.myTrades(BinanceTradeServiceRaw.java:152)
  at org.knowm.xchange.binance.service.BinanceTradeService.getTradeHistory(BinanceTradeService.java:278)
  ... 10 more

Exchange log
2021-02-04 09:34:15 DEBUG ExchangeOrderLog - ------------
2021-02-04 09:34:15 DEBUG ExchangeOrderLog - LT ADA/USDT using base amount 35819.60000000, price: 0.43115000
2021-02-04 09:34:15 DEBUG ExchangeOrderLog - Live trade ADA/USDT market order: buy? true, sell? false
2021-02-04 09:34:15 DEBUG ExchangeOrderLog - Created order: Order [type=BID, originalAmount=35819.6, cumulativeAmount=null, averagePrice=null, fee=null, currencyPair=ADA/USDT, id=STznrU5rN48CpNNWSr4HgfUk, timestamp=Thu Feb 04 09:34:15 CET 2021, status=null, flags=[], userReference=171059747] - sending to exchange
2021-02-04 09:34:15 DEBUG ExchangeOrderLog - ADA/USDT Market order BID outputting: Account has insufficient balance for requested action.

**Comment by COBRA-StakePool** [comment]
Very unstable
Livetrade:
![image](https://user-images.githubusercontent.com/75507851/107086102-cd12a180-67f9-11eb-9c21-83928f54e565.png)
papertrade:
![image](https://user-images.githubusercontent.com/75507851/107086300-17941e00-67fa-11eb-89af-efc70d0e798d.png)

**Comment by COBRA-StakePool** [comment]
2021-02-05 22:04:09 DEBUG ExchangeOrderLog - LT ADA/ETH using base amount 30446.00000000, price: 0.00031843
2021-02-05 22:04:09 DEBUG ExchangeOrderLog - Live trade ADA/ETH market order: buy? true, sell? false
2021-02-05 22:04:09 DEBUG ExchangeOrderLog - Created order: Order [type=BID, originalAmount=30446, cumulativeAmount=null, averagePrice=null, fee=null, currencyPair=ADA/ETH, id=w59NZsWzgDqNxwRjZ2WH4Gfz, timestamp=Fri Feb 05 22:04:09 CET 2021, status=null, flags=[], userReference=103699807] - sending to exchange
2021-02-05 22:04:10 DEBUG ExchangeOrderLog - ADA/ETH Market order BID outputting: Account has insufficient balance for requested action.

**Comment by COBRA-StakePool** [comment]
looks like it aint updating the value of your holdings fast enough. so it sends a order that's higher
Reduced from 100% to 98% and it did buy in

**Comment by nibarulabs** [comment]
This is the first problem:
```
Timestamp for this request is outside of the recvWindow.
```

That means that the bot set a timestamp at the time of order creation and the exchange rejected it because the request is too old.

What can cause this?
* a slow or interrupted connection
* a slow computer

The bot has been tested quite a bit in this regard and there shouldn't really be a reason why an order can't be placed in a timely manner. I think the recv window is set for about 5 seconds.

It is NOT recommended to run this on a laptop with wifi. The bot needs a stable connection, reasonably fast disk, and a low process load. I bring this up because people have tried to run the bot in all kinds of substandard situations; on Atom laptops, slow wifi, on a mining rig, on a video production machine (while crunching video), on a gaming rig (while playing games).
If you can't get a 'clean' machine, consider checking out acuitashosting.com for a vps with a dedicated high bandwidth connection.

If there other issues above are not part of this issue, please file them as their own separate issues.
